Add support for Mi Voice

diff --git a/tools/update-binary-cleaner b/tools/update-binary-cleaner
--- a/tools/update-binary-cleaner
+++ b/tools/update-binary-cleaner
@@ -128,6 +128,9 @@ fi
 if [ -d ./system/app ]; then
     cp -R ./system/app/* ${imgroot}/system/app/ || abort "Failed to copy apps"
 fi
+if [ -d ./system/data-app ]; then
+    cp -R ./system/data-app/* ${imgroot}/system/app/ || abort "Failed to copy data-apps"
+fi
 if [ -d ./system/framework ]; then
     cp -R ./system/framework/* ${imgroot}/system/framework/ || abort "Failed to copy frameworks"
 fi
